"""Bar & Column charts. Specs are Vega-Lite WITHOUT config/data/width/height
(the build script injects Du Bois config + databricks_query binding + container
sizing). Each chart binds to a dataset defined by `sql`; `fields` lists every
column the spec references (must match the SQL output aliases)."""

CATEGORY = "Bar & Column"

CHARTS = [
    {
        "id": "bar_simple", "title": "Simple Bar Chart",
        "sql": "SELECT * FROM VALUES ('A',28),('B',55),('C',43),('D',91),('E',81),('F',53),('G',19),('H',87),('I',52) AS t(category, amount)",
        "fields": ["category", "amount"],
        "spec": {"mark": "bar",
                 "encoding": {"x": {"field": "category", "type": "nominal", "axis": {"labelAngle": 0}},
                              "y": {"field": "amount", "type": "quantitative"}}},
    },
    {
        "id": "bar_aggregate", "title": "Aggregate Bar — Avg MPG by Origin",
        "sql": "SELECT Origin AS origin, ROUND(AVG(Miles_per_Gallon),1) AS avg_mpg FROM pb_demo.custom_gallery.cars GROUP BY Origin",
        "fields": ["origin", "avg_mpg"],
        "spec": {"mark": "bar",
                 "encoding": {"x": {"field": "avg_mpg", "type": "quantitative", "title": "Avg Miles per Gallon"},
                              "y": {"field": "origin", "type": "nominal", "title": None}}},
    },
    {
        "id": "bar_sorted", "title": "Sorted Bar — Deaths by Disaster",
        "sql": "SELECT Entity AS entity, SUM(Deaths) AS deaths FROM pb_demo.custom_gallery.disasters WHERE Entity <> 'All natural disasters' GROUP BY Entity",
        "fields": ["entity", "deaths"],
        "spec": {"mark": "bar",
                 "encoding": {"y": {"field": "entity", "type": "nominal", "sort": "-x", "title": None},
                              "x": {"field": "deaths", "type": "quantitative", "title": "Deaths"}}},
    },
    {
        "id": "bar_grouped", "title": "Grouped Bar — Population by Age & Sex (2000)",
        "sql": "SELECT age, CASE sex WHEN 1 THEN 'Male' ELSE 'Female' END AS gender, SUM(people) AS people FROM pb_demo.custom_gallery.population WHERE year=2000 GROUP BY age, sex",
        "fields": ["age", "gender", "people"],
        "spec": {"mark": "bar",
                 "encoding": {"x": {"field": "age", "type": "ordinal", "title": "Age", "axis": {"labelAngle": 0}},
                              "xOffset": {"field": "gender", "type": "nominal"},
                              "y": {"field": "people", "type": "quantitative"},
                              "color": {"field": "gender", "type": "nominal", "title": "Sex"}}},
    },
    {
        "id": "bar_stacked", "title": "Stacked Bar — Weather Days by Month",
        "sql": "SELECT month(date) AS month, weather, COUNT(*) AS count FROM pb_demo.custom_gallery.seattle_weather GROUP BY month(date), weather",
        "fields": ["month", "weather", "count"],
        "spec": {"mark": "bar",
                 "encoding": {"x": {"field": "month", "type": "ordinal", "axis": {"labelAngle": 0}},
                              "y": {"field": "count", "type": "quantitative"},
                              "color": {"field": "weather", "type": "nominal"}}},
    },
    {
        "id": "bar_normalized", "title": "Normalized Stacked Bar — Weather Share",
        "sql": "SELECT month(date) AS month, weather, COUNT(*) AS count FROM pb_demo.custom_gallery.seattle_weather GROUP BY month(date), weather",
        "fields": ["month", "weather", "count"],
        "spec": {"mark": "bar",
                 "encoding": {"x": {"field": "month", "type": "ordinal", "axis": {"labelAngle": 0}},
                              "y": {"field": "count", "type": "quantitative", "stack": "normalize", "title": "Share"},
                              "color": {"field": "weather", "type": "nominal"}}},
    },
    {
        "id": "bar_layered", "title": "Layered Bar — Male vs Female by Age (2000)",
        "sql": "SELECT age, CASE sex WHEN 1 THEN 'Male' ELSE 'Female' END AS gender, SUM(people) AS people FROM pb_demo.custom_gallery.population WHERE year=2000 GROUP BY age, sex",
        "fields": ["age", "gender", "people"],
        "spec": {"mark": {"type": "bar", "opacity": 0.7},
                 "encoding": {"x": {"field": "age", "type": "ordinal", "axis": {"labelAngle": 0}},
                              "y": {"field": "people", "type": "quantitative", "stack": None},
                              "color": {"field": "gender", "type": "nominal", "title": "Sex"}}},
    },
    {
        "id": "bar_highlight", "title": "Bar with Highlight — Max Origin",
        "sql": "SELECT Origin AS origin, ROUND(AVG(Miles_per_Gallon),1) AS avg_mpg FROM pb_demo.custom_gallery.cars GROUP BY Origin",
        "fields": ["origin", "avg_mpg"],
        "spec": {"mark": "bar",
                 "encoding": {"x": {"field": "origin", "type": "nominal", "axis": {"labelAngle": 0}, "title": None},
                              "y": {"field": "avg_mpg", "type": "quantitative", "title": "Avg MPG"},
                              "color": {"condition": {"test": "datum.avg_mpg >= 30", "value": "#F69E23"},
                                        "value": "#5593F7"}}},
    },
    {
        "id": "bar_labels", "title": "Bar with Value Labels",
        "sql": "SELECT Origin AS origin, COUNT(*) AS n FROM pb_demo.custom_gallery.cars GROUP BY Origin",
        "fields": ["origin", "n"],
        "spec": {"layer": [
            {"mark": "bar", "encoding": {"x": {"field": "n", "type": "quantitative", "title": "Count"},
                                          "y": {"field": "origin", "type": "nominal", "title": None}}},
            {"mark": {"type": "text", "align": "left", "dx": 4},
             "encoding": {"x": {"field": "n", "type": "quantitative"},
                          "y": {"field": "origin", "type": "nominal"},
                          "text": {"field": "n", "type": "quantitative"}}}
        ]},
    },
    {
        "id": "bar_meanline", "title": "Bar + Mean Rule — MPG by Cylinders",
        "sql": "SELECT CAST(Cylinders AS STRING) AS cylinders, ROUND(AVG(Miles_per_Gallon),1) AS avg_mpg FROM pb_demo.custom_gallery.cars WHERE Miles_per_Gallon IS NOT NULL GROUP BY Cylinders",
        "fields": ["cylinders", "avg_mpg"],
        "spec": {"layer": [
            {"mark": "bar", "encoding": {"x": {"field": "cylinders", "type": "ordinal", "axis": {"labelAngle": 0}},
                                          "y": {"field": "avg_mpg", "type": "quantitative", "title": "Avg MPG"}}},
            {"mark": {"type": "rule", "color": "#EC516D", "strokeWidth": 2},
             "encoding": {"y": {"aggregate": "mean", "field": "avg_mpg", "type": "quantitative"}}}
        ]},
    },
    {
        "id": "bar2_hstacked", "title": "Horizontal Stacked Bar — Weather Days by Month",
        "sql": "SELECT month(date) AS month, weather, COUNT(*) AS count FROM pb_demo.custom_gallery.seattle_weather GROUP BY month(date), weather",
        "fields": ["month", "weather", "count"],
        "spec": {"mark": "bar",
                 "encoding": {"y": {"field": "month", "type": "ordinal", "title": "Month"},
                              "x": {"field": "count", "type": "quantitative", "stack": True},
                              "color": {"field": "weather", "type": "nominal"}}},
    },
    {
        "id": "bar2_normalized_labels", "title": "Normalized Stacked Bar with % Labels",
        "sql": "SELECT month, weather, cnt, ROUND(100.0*cnt/SUM(cnt) OVER (PARTITION BY month),0) AS pct FROM (SELECT month(date) AS month, weather, COUNT(*) AS cnt FROM pb_demo.custom_gallery.seattle_weather GROUP BY month(date), weather)",
        "fields": ["month", "weather", "cnt", "pct"],
        "spec": {"layer": [
            {"mark": "bar",
             "encoding": {"x": {"field": "month", "type": "ordinal", "axis": {"labelAngle": 0}},
                          "y": {"field": "cnt", "type": "quantitative", "stack": "normalize", "title": "Share"},
                          "color": {"field": "weather", "type": "nominal"}}},
            {"mark": {"type": "text", "color": "white", "fontSize": 9},
             "encoding": {"x": {"field": "month", "type": "ordinal"},
                          "y": {"field": "cnt", "type": "quantitative", "stack": "normalize"},
                          "detail": {"field": "weather", "type": "nominal"},
                          "text": {"field": "pct", "type": "quantitative", "format": ".0f"}}}
        ]},
    },
    {
        "id": "bar2_gantt", "title": "Gantt Chart — Ranged Bars",
        "sql": "SELECT * FROM VALUES ('Design',0,3),('Build',3,8),('Test',7,10),('Deploy',9,12) AS t(task, start, end)",
        "fields": ["task", "start", "end"],
        "spec": {"mark": "bar",
                 "encoding": {"y": {"field": "task", "type": "nominal", "title": None,
                                    "sort": {"field": "start", "op": "min"}},
                              "x": {"field": "start", "type": "quantitative", "title": "Day"},
                              "x2": {"field": "end"}}},
    },
    {
        "id": "bar2_data_colors", "title": "Bar with Colors Encoded in Data",
        "sql": "SELECT * FROM VALUES ('A',28,'#5593F7'),('B',55,'#F69E23'),('C',43,'#EC516D'),('D',91,'#4A7C59'),('E',81,'#8250DF') AS t(category, amount, color)",
        "fields": ["category", "amount", "color"],
        "spec": {"mark": "bar",
                 "encoding": {"x": {"field": "category", "type": "nominal", "axis": {"labelAngle": 0}},
                              "y": {"field": "amount", "type": "quantitative"},
                              "color": {"field": "color", "type": "nominal", "scale": None, "legend": None}}},
    },
    {
        "id": "bar2_pyramid", "title": "Population Pyramid — Diverging (2000)",
        "sql": "SELECT age, CASE sex WHEN 1 THEN 'Male' ELSE 'Female' END AS gender, CASE WHEN sex=1 THEN -SUM(people) ELSE SUM(people) END AS people FROM pb_demo.custom_gallery.population WHERE year=2000 GROUP BY age, sex",
        "fields": ["age", "gender", "people"],
        "spec": {"mark": "bar",
                 "encoding": {"x": {"field": "people", "type": "quantitative", "title": "Population", "axis": {"format": "s"}},
                              "y": {"field": "age", "type": "ordinal", "sort": "descending", "title": "Age"},
                              "color": {"field": "gender", "type": "nominal", "title": "Sex"}}},
    },
    {
        "id": "bar2_likert", "title": "Diverging Stacked Bar — Likert Sentiment",
        "sql": "SELECT * FROM VALUES ('Onboarding','1 Strongly Disagree',-5),('Onboarding','2 Disagree',-12),('Onboarding','3 Neutral',9),('Onboarding','4 Agree',22),('Onboarding','5 Strongly Agree',14),('Support','1 Strongly Disagree',-8),('Support','2 Disagree',-18),('Support','3 Neutral',6),('Support','4 Agree',16),('Support','5 Strongly Agree',10),('Docs','1 Strongly Disagree',-3),('Docs','2 Disagree',-7),('Docs','3 Neutral',12),('Docs','4 Agree',25),('Docs','5 Strongly Agree',20) AS t(question, sentiment, count)",
        "fields": ["question", "sentiment", "count"],
        "spec": {"mark": "bar",
                 "encoding": {"x": {"field": "count", "type": "quantitative", "title": "Responses"},
                              "y": {"field": "question", "type": "nominal", "title": None},
                              "color": {"field": "sentiment", "type": "nominal", "title": "Sentiment",
                                        "scale": {"scheme": "redyellowblue"}},
                              "order": {"field": "sentiment", "type": "ordinal"}}},
    },
    {
        "id": "bar2_negative", "title": "Bar with Negative Values — Nonfarm Change",
        "sql": "SELECT to_date(month) AS month, nonfarm_change FROM pb_demo.custom_gallery.us_employment WHERE nonfarm_change IS NOT NULL AND to_date(month) >= DATE'2008-01-01' ORDER BY month",
        "fields": ["month", "nonfarm_change"],
        "spec": {"mark": "bar",
                 "encoding": {"x": {"field": "month", "type": "temporal", "title": None},
                              "y": {"field": "nonfarm_change", "type": "quantitative", "title": "Monthly Change (000s)"},
                              "color": {"condition": {"test": "datum.nonfarm_change < 0", "value": "#EC516D"},
                                        "value": "#5593F7"}}},
    },
    {
        "id": "bar2_month_initials", "title": "Bar with Month Initials",
        "sql": "SELECT month(date) AS month, COUNT(*) AS count FROM pb_demo.custom_gallery.seattle_weather GROUP BY month(date)",
        "fields": ["month", "count"],
        "spec": {"mark": "bar",
                 "encoding": {"x": {"field": "month", "type": "ordinal", "title": None,
                                    "axis": {"labelAngle": 0,
                                             "labelExpr": "['J','F','M','A','M','J','J','A','S','O','N','D'][datum.value-1]"}},
                              "y": {"field": "count", "type": "quantitative", "title": "Days"}}},
    },
    {
        "id": "bar2_argmax", "title": "Argmax Bar — Fastest Car per Origin",
        "sql": "SELECT origin, name, horsepower FROM (SELECT Origin AS origin, Name AS name, Horsepower AS horsepower, ROW_NUMBER() OVER (PARTITION BY Origin ORDER BY Horsepower DESC) AS rn FROM pb_demo.custom_gallery.cars WHERE Horsepower IS NOT NULL) WHERE rn=1",
        "fields": ["origin", "name", "horsepower"],
        "spec": {"layer": [
            {"mark": "bar",
             "encoding": {"x": {"field": "horsepower", "type": "quantitative", "title": "Max Horsepower"},
                          "y": {"field": "origin", "type": "nominal", "sort": "-x", "title": None}}},
            {"mark": {"type": "text", "align": "left", "dx": 4},
             "encoding": {"x": {"field": "horsepower", "type": "quantitative"},
                          "y": {"field": "origin", "type": "nominal", "sort": "-x"},
                          "text": {"field": "name", "type": "nominal"}}}
        ]},
    },
    {
        "id": "bar2_inside_labels", "title": "Bar with Inside Label Overlays",
        "sql": "SELECT Origin AS origin, COUNT(*) AS n FROM pb_demo.custom_gallery.cars GROUP BY Origin",
        "fields": ["origin", "n"],
        "spec": {"layer": [
            {"mark": "bar",
             "encoding": {"x": {"field": "n", "type": "quantitative", "title": "Count"},
                          "y": {"field": "origin", "type": "nominal", "title": None}}},
            {"mark": {"type": "text", "align": "right", "dx": -6, "color": "white", "fontWeight": "bold"},
             "encoding": {"x": {"field": "n", "type": "quantitative"},
                          "y": {"field": "origin", "type": "nominal"},
                          "text": {"field": "n", "type": "quantitative"}}}
        ]},
    },
    {
        "id": "g3_bar_size_responsive", "title": "Responsive Bar — Cars by Origin",
        "sql": "SELECT Origin AS origin, COUNT(*) AS n FROM pb_demo.custom_gallery.cars GROUP BY Origin",
        "fields": ["origin", "n"],
        "spec": {"mark": "bar",
                 "encoding": {"x": {"field": "origin", "type": "nominal", "axis": {"labelAngle": 0}, "title": None},
                              "y": {"field": "n", "type": "quantitative", "title": "Number of Cars"}}},
    },
    {
        "id": "g3_stacked_bar_count_corner_radius_mark", "title": "Stacked Bar — Rounded Corners",
        "sql": "SELECT month(date) AS month, weather, COUNT(*) AS count FROM pb_demo.custom_gallery.seattle_weather GROUP BY month(date), weather",
        "fields": ["month", "weather", "count"],
        "spec": {"mark": {"type": "bar", "cornerRadiusTopLeft": 3, "cornerRadiusTopRight": 3},
                 "encoding": {"x": {"field": "month", "type": "ordinal", "axis": {"labelAngle": 0}},
                              "y": {"field": "count", "type": "quantitative", "title": "Days"},
                              "color": {"field": "weather", "type": "nominal"}}},
    },
    {
        "id": "g3_layer_bar_labels_grey", "title": "Bar with Labels — Grey Below Threshold",
        "sql": "SELECT Major_Genre AS genre, ROUND(AVG(IMDB_Rating),2) AS mean_rating FROM pb_demo.custom_gallery.movies WHERE Major_Genre IS NOT NULL AND IMDB_Rating IS NOT NULL GROUP BY Major_Genre",
        "fields": ["genre", "mean_rating"],
        "spec": {"layer": [
            {"mark": "bar",
             "encoding": {"y": {"field": "genre", "type": "nominal", "sort": "-x", "title": None},
                          "x": {"field": "mean_rating", "type": "quantitative", "title": "Mean IMDB Rating",
                                "scale": {"domain": [0, 10]}},
                          "color": {"condition": {"test": "datum.mean_rating < 6.5", "value": "#C9CDD3"},
                                    "value": "#5593F7"}}},
            {"mark": {"type": "text", "align": "left", "dx": 4},
             "encoding": {"y": {"field": "genre", "type": "nominal", "sort": "-x"},
                          "x": {"field": "mean_rating", "type": "quantitative"},
                          "text": {"field": "mean_rating", "type": "quantitative", "format": ".1f"},
                          "color": {"condition": {"test": "datum.mean_rating < 6.5", "value": "#C9CDD3"},
                                    "value": "#5593F7"}}}
        ]},
    },
    {
        "id": "g3_bar_month_temporal_band_center", "title": "Monthly Precipitation — Temporal Band Center",
        "sql": "SELECT to_date(concat('2015-', lpad(CAST(month(date) AS STRING),2,'0'), '-01')) AS month, ROUND(AVG(precipitation),2) AS avg_precip FROM pb_demo.custom_gallery.seattle_weather GROUP BY month(date) ORDER BY month",
        "fields": ["month", "avg_precip"],
        "spec": {"mark": "bar",
                 "encoding": {"x": {"field": "month", "type": "temporal", "timeUnit": "month",
                                    "bandPosition": 0.5, "title": None},
                              "y": {"field": "avg_precip", "type": "quantitative", "title": "Mean Precipitation"}}},
    },
    {
        "id": "g3_bar_axis_space_saving", "title": "Bar with Space-Saving Axis",
        "sql": "SELECT Origin AS origin, COUNT(*) AS n FROM pb_demo.custom_gallery.cars GROUP BY Origin",
        "fields": ["origin", "n"],
        "spec": {"mark": {"type": "bar", "yOffset": 5, "cornerRadiusEnd": 2, "height": {"band": 0.5}},
                 "encoding": {"y": {"field": "origin", "type": "nominal", "sort": "-x",
                                    "scale": {"padding": 0},
                                    "axis": {"bandPosition": 0, "grid": True, "domain": False, "ticks": False,
                                             "labelAlign": "left", "labelBaseline": "bottom",
                                             "labelPadding": -5, "labelOffset": -14, "title": None,
                                             "labelColor": "#E8ECF0", "labelFontWeight": "bold",
                                             "labelFontSize": 12, "zindex": 1}},
                              "x": {"field": "n", "type": "quantitative", "axis": {"grid": False},
                                    "title": "Number of Cars"}}},
    },
    {
        "id": "g3_bar_heatlane", "title": "Heat Lane — Horsepower Distribution",
        "sql": "WITH b AS (SELECT FLOOR(Horsepower/25)*25 AS bin_start, FLOOR(Horsepower/25)*25+25 AS bin_end, COUNT(*) AS cnt FROM pb_demo.custom_gallery.cars WHERE Horsepower IS NOT NULL GROUP BY FLOOR(Horsepower/25)*25) SELECT bin_start, bin_end, cnt, cnt/2.0 AS y, -cnt/2.0 AS y2, MAX(cnt) OVER () AS max_cnt FROM b ORDER BY bin_start",
        "fields": ["bin_start", "bin_end", "cnt", "y", "y2", "max_cnt"],
        "spec": {"encoding": {"x": {"field": "bin_start", "type": "quantitative", "title": "Horsepower",
                                     "axis": {"grid": False}},
                              "x2": {"field": "bin_end"},
                              "y": {"field": "y", "type": "quantitative", "axis": None},
                              "y2": {"field": "y2"}},
                 "layer": [
                     {"mark": {"type": "bar", "xOffset": 2, "x2Offset": -2, "cornerRadius": 3},
                      "encoding": {"color": {"field": "max_cnt", "type": "ordinal", "title": "count",
                                             "scale": {"scheme": "lighttealblue"}, "legend": None}}},
                     {"mark": {"type": "bar", "xOffset": 2, "x2Offset": -2, "yOffset": -3, "y2Offset": 3},
                      "encoding": {"color": {"field": "cnt", "type": "ordinal", "title": "count"}}}
                 ]},
        "w": 3,
    },
    {
        "id": "g3_bar_negative_horizontal_label", "title": "Horizontal Negative Bar with Labels",
        "sql": "SELECT * FROM VALUES ('A',-28),('B',55),('C',-33),('D',91),('E',81),('F',53),('G',-19),('H',87),('I',52) AS t(category, amount)",
        "fields": ["category", "amount"],
        "spec": {"encoding": {"y": {"field": "category", "type": "nominal", "title": None,
                                     "axis": {"domain": False, "ticks": False, "labelAngle": 0, "labelPadding": 4}},
                              "x": {"field": "amount", "type": "quantitative", "scale": {"padding": 20},
                                    "axis": {"gridColor": {"condition": {"test": "datum.value === 0", "value": "#888"},
                                                           "value": "#ddd"}}}},
                 "layer": [
                     {"mark": "bar",
                      "encoding": {"color": {"condition": {"test": "datum.amount < 0", "value": "#EC516D"},
                                             "value": "#5593F7"}}},
                     {"mark": {"type": "text",
                               "align": {"expr": "datum.amount < 0 ? 'right' : 'left'"},
                               "dx": {"expr": "datum.amount < 0 ? -2 : 2"}},
                      "encoding": {"text": {"field": "amount", "type": "quantitative"}}}
                 ]},
    },
]
