"""Correlation & Scatter charts."""

CATEGORY = "Correlation & Scatter"

_CARS_XY = "SELECT Horsepower AS horsepower, Miles_per_Gallon AS miles_per_gallon FROM pb_demo.custom_gallery.cars WHERE Horsepower IS NOT NULL AND Miles_per_Gallon IS NOT NULL"

CHARTS = [
    {
        "id": "corr_scatter_basic", "title": "Scatter — Horsepower vs MPG",
        "sql": _CARS_XY,
        "fields": ["horsepower", "miles_per_gallon"],
        "spec": {"mark": {"type": "point", "filled": True, "size": 60, "opacity": 0.6},
                 "encoding": {"x": {"field": "horsepower", "type": "quantitative", "title": "Horsepower",
                                    "scale": {"zero": False}},
                              "y": {"field": "miles_per_gallon", "type": "quantitative", "title": "Miles per Gallon",
                                    "scale": {"zero": False}}}},
    },
    {
        "id": "corr_scatter_color", "title": "Scatter by Origin",
        "sql": "SELECT Horsepower AS horsepower, Miles_per_Gallon AS miles_per_gallon, Origin AS origin FROM pb_demo.custom_gallery.cars WHERE Horsepower IS NOT NULL AND Miles_per_Gallon IS NOT NULL",
        "fields": ["horsepower", "miles_per_gallon", "origin"],
        "spec": {"mark": {"type": "point", "filled": True, "size": 60, "opacity": 0.7},
                 "encoding": {"x": {"field": "horsepower", "type": "quantitative", "title": "Horsepower",
                                    "scale": {"zero": False}},
                              "y": {"field": "miles_per_gallon", "type": "quantitative", "title": "Miles per Gallon",
                                    "scale": {"zero": False}},
                              "color": {"field": "origin", "type": "nominal", "title": "Origin"}}},
    },
    {
        "id": "corr_bubble", "title": "Bubble — Size by Weight",
        "sql": "SELECT Horsepower AS horsepower, Miles_per_Gallon AS miles_per_gallon, Weight_in_lbs AS weight_in_lbs FROM pb_demo.custom_gallery.cars WHERE Horsepower IS NOT NULL AND Miles_per_Gallon IS NOT NULL AND Weight_in_lbs IS NOT NULL",
        "fields": ["horsepower", "miles_per_gallon", "weight_in_lbs"],
        "spec": {"mark": {"type": "point", "filled": True, "opacity": 0.5, "color": "#5593F7"},
                 "encoding": {"x": {"field": "horsepower", "type": "quantitative", "title": "Horsepower",
                                    "scale": {"zero": False}},
                              "y": {"field": "miles_per_gallon", "type": "quantitative", "title": "Miles per Gallon",
                                    "scale": {"zero": False}},
                              "size": {"field": "weight_in_lbs", "type": "quantitative", "title": "Weight (lbs)",
                                       "scale": {"range": [20, 500]}}}},
    },
    {
        "id": "corr_regression", "title": "Scatter with Regression Line",
        "sql": _CARS_XY,
        "fields": ["horsepower", "miles_per_gallon"],
        "spec": {"layer": [
            {"mark": {"type": "point", "filled": True, "size": 55, "opacity": 0.45, "color": "#5593F7"},
             "encoding": {"x": {"field": "horsepower", "type": "quantitative", "title": "Horsepower",
                                "scale": {"zero": False}},
                          "y": {"field": "miles_per_gallon", "type": "quantitative", "title": "Miles per Gallon",
                                "scale": {"zero": False}}}},
            {"transform": [{"regression": "miles_per_gallon", "on": "horsepower"}],
             "mark": {"type": "line", "color": "#EC516D", "strokeWidth": 3},
             "encoding": {"x": {"field": "horsepower", "type": "quantitative"},
                          "y": {"field": "miles_per_gallon", "type": "quantitative"}}}
        ]},
    },
    {
        "id": "corr_loess", "title": "Scatter with LOESS Trend",
        "sql": _CARS_XY,
        "fields": ["horsepower", "miles_per_gallon"],
        "spec": {"layer": [
            {"mark": {"type": "point", "filled": True, "size": 55, "opacity": 0.45, "color": "#5593F7"},
             "encoding": {"x": {"field": "horsepower", "type": "quantitative", "title": "Horsepower",
                                "scale": {"zero": False}},
                          "y": {"field": "miles_per_gallon", "type": "quantitative", "title": "Miles per Gallon",
                                "scale": {"zero": False}}}},
            {"transform": [{"loess": "miles_per_gallon", "on": "horsepower"}],
             "mark": {"type": "line", "color": "#F69E23", "strokeWidth": 3},
             "encoding": {"x": {"field": "horsepower", "type": "quantitative"},
                          "y": {"field": "miles_per_gallon", "type": "quantitative"}}}
        ]},
    },
    {
        "id": "corr_log_scale", "title": "Log-Scale Scatter — Gapminder 2000",
        "sql": "SELECT fertility, life_expect, pop, CAST(cluster AS STRING) AS cluster FROM pb_demo.custom_gallery.gapminder WHERE year=2000",
        "fields": ["fertility", "life_expect", "pop", "cluster"],
        "spec": {"mark": {"type": "point", "filled": True, "opacity": 0.7},
                 "encoding": {"x": {"field": "fertility", "type": "quantitative", "title": "Fertility rate",
                                    "scale": {"type": "log"}},
                              "y": {"field": "life_expect", "type": "quantitative", "title": "Life expectancy",
                                    "scale": {"zero": False}},
                              "size": {"field": "pop", "type": "quantitative", "title": "Population",
                                       "scale": {"range": [20, 800]}},
                              "color": {"field": "cluster", "type": "nominal", "title": "Cluster"}}},
    },
    {
        "id": "corr_binned", "title": "Binned Scatter — Count by Cell",
        "sql": _CARS_XY,
        "fields": ["horsepower", "miles_per_gallon"],
        "spec": {"mark": {"type": "circle", "color": "#5593F7"},
                 "encoding": {"x": {"field": "horsepower", "type": "quantitative", "bin": {"maxbins": 12},
                                    "title": "Horsepower"},
                              "y": {"field": "miles_per_gallon", "type": "quantitative", "bin": {"maxbins": 12},
                                    "title": "Miles per Gallon"},
                              "size": {"aggregate": "count", "type": "quantitative", "title": "Count"}}},
    },
    {
        "id": "corr_connected", "title": "Connected Scatter — Driving Miles vs Gas",
        "sql": "SELECT year, miles, gas FROM pb_demo.custom_gallery.driving ORDER BY year",
        "fields": ["year", "miles", "gas"],
        "spec": {"layer": [
            {"mark": {"type": "line", "color": "#5593F7", "opacity": 0.7},
             "encoding": {"x": {"field": "miles", "type": "quantitative", "title": "Miles driven per capita",
                                "scale": {"zero": False}},
                          "y": {"field": "gas", "type": "quantitative", "title": "Gas price ($)",
                                "scale": {"zero": False}},
                          "order": {"field": "year", "type": "quantitative"}}},
            {"mark": {"type": "point", "filled": True, "size": 55, "color": "#5593F7"},
             "encoding": {"x": {"field": "miles", "type": "quantitative"},
                          "y": {"field": "gas", "type": "quantitative"}}}
        ]},
    },
    {
        "id": "corr_text_scatter", "title": "Text-Mark Scatter — Top Populations 2000",
        "sql": "SELECT country, fertility, life_expect, pop FROM pb_demo.custom_gallery.gapminder WHERE year=2000 ORDER BY pop DESC LIMIT 15",
        "fields": ["country", "fertility", "life_expect", "pop"],
        "spec": {"layer": [
            {"mark": {"type": "point", "filled": True, "size": 40, "color": "#5593F7", "opacity": 0.6},
             "encoding": {"x": {"field": "fertility", "type": "quantitative", "title": "Fertility rate",
                                "scale": {"zero": False}},
                          "y": {"field": "life_expect", "type": "quantitative", "title": "Life expectancy",
                                "scale": {"zero": False}}}},
            {"mark": {"type": "text", "align": "left", "dx": 6, "fontSize": 9},
             "encoding": {"x": {"field": "fertility", "type": "quantitative"},
                          "y": {"field": "life_expect", "type": "quantitative"},
                          "text": {"field": "country", "type": "nominal"}}}
        ]},
    },
    {
        "id": "corr_residual", "title": "Residual Plot — MPG ~ Horsepower",
        "sql": "WITH params AS (SELECT regr_slope(Miles_per_Gallon, Horsepower) AS slope, regr_intercept(Miles_per_Gallon, Horsepower) AS intercept FROM pb_demo.custom_gallery.cars WHERE Miles_per_Gallon IS NOT NULL AND Horsepower IS NOT NULL) SELECT c.Horsepower AS horsepower, ROUND(c.Miles_per_Gallon - (p.slope*c.Horsepower + p.intercept), 2) AS residual FROM pb_demo.custom_gallery.cars c CROSS JOIN params p WHERE c.Miles_per_Gallon IS NOT NULL AND c.Horsepower IS NOT NULL",
        "fields": ["horsepower", "residual"],
        "spec": {"layer": [
            {"mark": {"type": "rule", "color": "#EC516D", "strokeWidth": 2},
             "encoding": {"y": {"datum": 0, "type": "quantitative"}}},
            {"mark": {"type": "point", "filled": True, "size": 55, "opacity": 0.5, "color": "#5593F7"},
             "encoding": {"x": {"field": "horsepower", "type": "quantitative", "title": "Horsepower",
                                "scale": {"zero": False}},
                          "y": {"field": "residual", "type": "quantitative", "title": "Residual (actual − fit MPG)"}}}
        ]},
    },
    {
        "id": "corr2_strip_1d", "title": "1D Strip Plot — Horsepower",
        "sql": "SELECT Horsepower AS horsepower FROM pb_demo.custom_gallery.cars WHERE Horsepower IS NOT NULL",
        "fields": ["horsepower"],
        "spec": {"mark": {"type": "tick", "opacity": 0.55, "color": "#5593F7"},
                 "encoding": {"x": {"field": "horsepower", "type": "quantitative", "title": "Horsepower"}}},
        "h": 4,
    },
    {
        "id": "corr2_strip_cylinders", "title": "Strip Plot — Horsepower by Cylinders",
        "sql": "SELECT Horsepower AS horsepower, Cylinders AS cylinders FROM pb_demo.custom_gallery.cars WHERE Horsepower IS NOT NULL",
        "fields": ["horsepower", "cylinders"],
        "spec": {"mark": {"type": "tick", "opacity": 0.7},
                 "encoding": {"x": {"field": "horsepower", "type": "quantitative", "title": "Horsepower"},
                              "y": {"field": "cylinders", "type": "ordinal", "title": "Cylinders"},
                              "color": {"field": "cylinders", "type": "ordinal", "title": "Cylinders", "legend": None}}},
    },
    {
        "id": "corr2_scatter_null_grey", "title": "Scatter with Null Values Shown in Grey",
        "sql": "SELECT Horsepower AS horsepower, Miles_per_Gallon AS miles_per_gallon FROM pb_demo.custom_gallery.cars",
        "fields": ["horsepower", "miles_per_gallon"],
        "spec": {"mark": {"type": "point", "filled": True, "size": 55, "opacity": 0.6, "invalid": None},
                 "encoding": {"x": {"field": "horsepower", "type": "quantitative", "title": "Horsepower",
                                    "scale": {"zero": False}},
                              "y": {"field": "miles_per_gallon", "type": "quantitative", "title": "Miles per Gallon",
                                    "scale": {"zero": False}},
                              "color": {"condition": {"test": "!isValid(datum.horsepower) || !isValid(datum.miles_per_gallon)",
                                                      "value": "#c7c7c7"},
                                        "value": "#5593F7"}}},
    },
    {
        "id": "corr2_scatter_filled", "title": "Scatter with Filled Circles",
        "sql": _CARS_XY,
        "fields": ["horsepower", "miles_per_gallon"],
        "spec": {"mark": {"type": "circle", "size": 70, "opacity": 0.6, "color": "#5593F7"},
                 "encoding": {"x": {"field": "horsepower", "type": "quantitative", "title": "Horsepower",
                                    "scale": {"zero": False}},
                              "y": {"field": "miles_per_gallon", "type": "quantitative", "title": "Miles per Gallon",
                                    "scale": {"zero": False}}}},
    },
    {
        "id": "corr2_bubble_disasters", "title": "Bubble — Natural Disaster Deaths by Year",
        "sql": "SELECT Year AS year, Entity AS entity, Deaths AS deaths FROM pb_demo.custom_gallery.disasters WHERE Entity IN ('Drought','Epidemic','Flood','Earthquake','Extreme weather') AND Deaths IS NOT NULL",
        "fields": ["year", "entity", "deaths"],
        "spec": {"mark": {"type": "circle", "opacity": 0.6},
                 "encoding": {"x": {"field": "year", "type": "quantitative", "title": "Year",
                                    "scale": {"zero": False}},
                              "y": {"field": "entity", "type": "nominal", "title": "Disaster type"},
                              "size": {"field": "deaths", "type": "quantitative", "title": "Deaths",
                                       "scale": {"range": [10, 600]}},
                              "color": {"field": "entity", "type": "nominal", "legend": None}}},
        "w": 3,
    },
    {
        "id": "corr2_dotplot_jitter", "title": "Dot Plot with Jitter — Horsepower by Origin",
        "sql": "SELECT Horsepower AS horsepower, Origin AS origin FROM pb_demo.custom_gallery.cars WHERE Horsepower IS NOT NULL",
        "fields": ["horsepower", "origin"],
        "spec": {"transform": [{"calculate": "random()", "as": "jitter"}],
                 "mark": {"type": "point", "filled": True, "size": 45, "opacity": 0.55},
                 "encoding": {"x": {"field": "horsepower", "type": "quantitative", "title": "Horsepower"},
                              "y": {"field": "origin", "type": "nominal", "title": "Origin"},
                              "yOffset": {"field": "jitter", "type": "quantitative"},
                              "color": {"field": "origin", "type": "nominal", "legend": None}}},
    },
    {
        "id": "corr2_parallel", "title": "Parallel Coordinates — Car Attributes (normalized)",
        "sql": "SELECT Name AS name, Origin AS origin, (Miles_per_Gallon - MIN(Miles_per_Gallon) OVER()) / (MAX(Miles_per_Gallon) OVER() - MIN(Miles_per_Gallon) OVER()) AS mpg_n, (Horsepower - MIN(Horsepower) OVER()) / (MAX(Horsepower) OVER() - MIN(Horsepower) OVER()) AS horsepower_n, (Weight_in_lbs - MIN(Weight_in_lbs) OVER()) / (MAX(Weight_in_lbs) OVER() - MIN(Weight_in_lbs) OVER()) AS weight_n, (Acceleration - MIN(Acceleration) OVER()) / (MAX(Acceleration) OVER() - MIN(Acceleration) OVER()) AS acceleration_n FROM pb_demo.custom_gallery.cars WHERE Miles_per_Gallon IS NOT NULL AND Horsepower IS NOT NULL AND Weight_in_lbs IS NOT NULL AND Acceleration IS NOT NULL",
        "fields": ["name", "origin", "mpg_n", "horsepower_n", "weight_n", "acceleration_n"],
        "spec": {"transform": [{"fold": ["mpg_n", "horsepower_n", "weight_n", "acceleration_n"],
                                "as": ["axis", "value"]}],
                 "mark": {"type": "line", "opacity": 0.3, "strokeWidth": 1},
                 "encoding": {"x": {"field": "axis", "type": "nominal", "title": "Attribute",
                                    "sort": ["mpg_n", "horsepower_n", "weight_n", "acceleration_n"]},
                              "y": {"field": "value", "type": "quantitative", "title": "Normalized value (0–1)"},
                              "color": {"field": "origin", "type": "nominal", "title": "Origin"},
                              "detail": {"field": "name", "type": "nominal"}}},
        "w": 3,
    },
    {
        "id": "corr2_scatter_mean_sd", "title": "Scatter with Mean ± Std Dev",
        "sql": _CARS_XY,
        "fields": ["horsepower", "miles_per_gallon"],
        "spec": {"layer": [
            {"transform": [{"aggregate": [{"op": "mean", "field": "horsepower", "as": "mx"},
                                          {"op": "stdev", "field": "horsepower", "as": "sx"},
                                          {"op": "mean", "field": "miles_per_gallon", "as": "my"},
                                          {"op": "stdev", "field": "miles_per_gallon", "as": "sy"}]},
                           {"calculate": "datum.mx - datum.sx", "as": "x_lo"},
                           {"calculate": "datum.mx + datum.sx", "as": "x_hi"},
                           {"calculate": "datum.my - datum.sy", "as": "y_lo"},
                           {"calculate": "datum.my + datum.sy", "as": "y_hi"}],
             "mark": {"type": "rect", "opacity": 0.12, "color": "#EC516D"},
             "encoding": {"x": {"field": "x_lo", "type": "quantitative"}, "x2": {"field": "x_hi"},
                          "y": {"field": "y_lo", "type": "quantitative"}, "y2": {"field": "y_hi"}}},
            {"mark": {"type": "point", "filled": True, "size": 50, "opacity": 0.4, "color": "#5593F7"},
             "encoding": {"x": {"field": "horsepower", "type": "quantitative", "title": "Horsepower",
                                "scale": {"zero": False}},
                          "y": {"field": "miles_per_gallon", "type": "quantitative", "title": "Miles per Gallon",
                                "scale": {"zero": False}}}},
            {"transform": [{"aggregate": [{"op": "mean", "field": "horsepower", "as": "mx"}]}],
             "mark": {"type": "rule", "color": "#EC516D", "strokeWidth": 2},
             "encoding": {"x": {"field": "mx", "type": "quantitative"}}},
            {"transform": [{"aggregate": [{"op": "mean", "field": "miles_per_gallon", "as": "my"}]}],
             "mark": {"type": "rule", "color": "#EC516D", "strokeWidth": 2},
             "encoding": {"y": {"field": "my", "type": "quantitative"}}}
        ]},
    },
    {
        "id": "g3_point_color_with_shape", "title": "Scatter — Color & Shape by Origin",
        "sql": "SELECT Horsepower AS horsepower, Miles_per_Gallon AS miles_per_gallon, Origin AS origin FROM pb_demo.custom_gallery.cars WHERE Horsepower IS NOT NULL AND Miles_per_Gallon IS NOT NULL",
        "fields": ["horsepower", "miles_per_gallon", "origin"],
        "spec": {"mark": {"type": "point", "filled": True, "size": 70, "opacity": 0.75},
                 "encoding": {"x": {"field": "horsepower", "type": "quantitative", "title": "Horsepower",
                                    "scale": {"zero": False}},
                              "y": {"field": "miles_per_gallon", "type": "quantitative", "title": "Miles per Gallon",
                                    "scale": {"zero": False}},
                              "color": {"field": "origin", "type": "nominal", "title": "Origin"},
                              "shape": {"field": "origin", "type": "nominal", "title": "Origin"}}},
    },
    {
        "id": "g3_circle_custom_tick_labels", "title": "Scatter with Custom Axis Tick Labels",
        "sql": _CARS_XY,
        "fields": ["horsepower", "miles_per_gallon"],
        "spec": {"mark": {"type": "circle", "size": 70, "opacity": 0.6, "color": "#5593F7"},
                 "encoding": {"x": {"field": "horsepower", "type": "quantitative", "title": "Horsepower",
                                    "scale": {"zero": False},
                                    "axis": {"values": [50, 100, 150, 200], "labelExpr": "datum.value + ' hp'"}},
                              "y": {"field": "miles_per_gallon", "type": "quantitative", "title": "Miles per Gallon",
                                    "scale": {"zero": False},
                                    "axis": {"values": [10, 20, 30, 40], "labelExpr": "datum.value + ' mpg'"}}}},
    },
]
