"""Line & Area charts."""

CATEGORY = "Line & Area"

CHARTS = [
    {
        "id": "line_simple", "title": "Simple Line — GOOG Price",
        "sql": "SELECT date, price FROM pb_demo.custom_gallery.stocks WHERE symbol='GOOG' ORDER BY date",
        "fields": ["date", "price"],
        "spec": {"mark": "line",
                 "encoding": {"x": {"field": "date", "type": "temporal", "title": None},
                              "y": {"field": "price", "type": "quantitative", "title": "Price ($)"}}},
    },
    {
        "id": "line_multi", "title": "Multi-Series Line — Stock Prices",
        "sql": "SELECT symbol, date, price FROM pb_demo.custom_gallery.stocks ORDER BY date",
        "fields": ["symbol", "date", "price"],
        "spec": {"mark": "line",
                 "encoding": {"x": {"field": "date", "type": "temporal", "title": None},
                              "y": {"field": "price", "type": "quantitative", "title": "Price ($)"},
                              "color": {"field": "symbol", "type": "nominal", "title": "Symbol"}}},
    },
    {
        "id": "line_points", "title": "Line with Point Markers",
        "sql": "SELECT year, wheat FROM pb_demo.custom_gallery.wheat ORDER BY year",
        "fields": ["year", "wheat"],
        "spec": {"mark": {"type": "line", "point": True},
                 "encoding": {"x": {"field": "year", "type": "quantitative", "title": "Year", "axis": {"format": "d"}},
                              "y": {"field": "wheat", "type": "quantitative", "title": "Wheat price (shillings)"}}},
    },
    {
        "id": "line_step", "title": "Step Chart — AAPL",
        "sql": "SELECT date, price FROM pb_demo.custom_gallery.stocks WHERE symbol='AAPL' ORDER BY date",
        "fields": ["date", "price"],
        "spec": {"mark": {"type": "line", "interpolate": "step-after"},
                 "encoding": {"x": {"field": "date", "type": "temporal", "title": None},
                              "y": {"field": "price", "type": "quantitative", "title": "Price ($)"}}},
    },
    {
        "id": "area_simple", "title": "Area Chart — S&P 500",
        "sql": "SELECT date, price FROM pb_demo.custom_gallery.sp500 ORDER BY date",
        "fields": ["date", "price"],
        "spec": {"mark": "area",
                 "encoding": {"x": {"field": "date", "type": "temporal", "title": None},
                              "y": {"field": "price", "type": "quantitative", "title": "Index"}}},
    },
    {
        "id": "area_stacked", "title": "Stacked Area — Iowa Electricity",
        "sql": "SELECT year, source, net_generation FROM pb_demo.custom_gallery.iowa_electricity ORDER BY year",
        "fields": ["year", "source", "net_generation"],
        "spec": {"mark": "area",
                 "encoding": {"x": {"field": "year", "type": "temporal", "title": None},
                              "y": {"field": "net_generation", "type": "quantitative", "title": "Net generation"},
                              "color": {"field": "source", "type": "nominal"}}},
    },
    {
        "id": "area_normalized", "title": "Normalized Stacked Area — Unemployment",
        "sql": "SELECT date, series, count FROM pb_demo.custom_gallery.unemployment_across_industries ORDER BY date",
        "fields": ["date", "series", "count"],
        "spec": {"mark": "area",
                 "encoding": {"x": {"field": "date", "type": "temporal", "title": None},
                              "y": {"field": "count", "type": "quantitative", "stack": "normalize", "title": "Share"},
                              "color": {"field": "series", "type": "nominal", "title": "Industry"}}},
    },
    {
        "id": "area_streamgraph", "title": "Streamgraph — Unemployment by Industry",
        "sql": "SELECT date, series, count FROM pb_demo.custom_gallery.unemployment_across_industries ORDER BY date",
        "fields": ["date", "series", "count"],
        "spec": {"mark": "area",
                 "encoding": {"x": {"field": "date", "type": "temporal", "title": None},
                              "y": {"field": "count", "type": "quantitative", "stack": "center", "axis": None},
                              "color": {"field": "series", "type": "nominal", "title": "Industry"}}},
    },
    {
        "id": "area_overlay", "title": "Area with Line Overlay — CO₂",
        "sql": "SELECT to_date(Date) AS date, CO2 AS co2 FROM pb_demo.custom_gallery.co2_concentration WHERE Date IS NOT NULL ORDER BY date",
        "fields": ["date", "co2"],
        "spec": {"mark": {"type": "area", "line": {"color": "#5593F7"}, "opacity": 0.5},
                 "encoding": {"x": {"field": "date", "type": "temporal", "title": None},
                              "y": {"field": "co2", "type": "quantitative", "scale": {"zero": False}, "title": "CO₂ (ppm)"}}},
    },
    {
        "id": "area_band", "title": "Temperature Band + Line — Seattle",
        "sql": "SELECT month(date) AS month, ROUND(AVG(temp_min),1) AS tmin, ROUND(AVG(temp_max),1) AS tmax, ROUND(AVG((temp_min+temp_max)/2),1) AS tavg FROM pb_demo.custom_gallery.seattle_weather GROUP BY month(date) ORDER BY month",
        "fields": ["month", "tmin", "tmax", "tavg"],
        "spec": {"layer": [
            {"mark": {"type": "area", "opacity": 0.3, "color": "#5593F7"},
             "encoding": {"x": {"field": "month", "type": "ordinal", "axis": {"labelAngle": 0}, "title": "Month"},
                          "y": {"field": "tmin", "type": "quantitative", "title": "Temp (°C)"},
                          "y2": {"field": "tmax"}}},
            {"mark": {"type": "line", "color": "#5593F7", "point": True},
             "encoding": {"x": {"field": "month", "type": "ordinal"},
                          "y": {"field": "tavg", "type": "quantitative"}}}
        ]},
    },
    {
        "id": "la2_line_stroked_points", "title": "Line with Stroked Point Markers — GOOG",
        "sql": "SELECT date, price FROM pb_demo.custom_gallery.stocks WHERE symbol='GOOG' ORDER BY date",
        "fields": ["date", "price"],
        "spec": {"mark": {"type": "line", "point": {"filled": False, "fill": "white"}},
                 "encoding": {"x": {"field": "date", "type": "temporal", "title": None},
                              "y": {"field": "price", "type": "quantitative", "title": "Price ($)"}}},
    },
    {
        "id": "la2_line_halo", "title": "Multi-Series Line with Halo Stroke",
        "sql": "SELECT symbol, date, price FROM pb_demo.custom_gallery.stocks ORDER BY date",
        "fields": ["symbol", "date", "price"],
        "spec": {"layer": [
            {"mark": {"type": "line", "stroke": "white", "strokeWidth": 4},
             "encoding": {"x": {"field": "date", "type": "temporal", "title": None},
                          "y": {"field": "price", "type": "quantitative", "title": "Price ($)"},
                          "detail": {"field": "symbol", "type": "nominal"}}},
            {"mark": {"type": "line", "strokeWidth": 1.5},
             "encoding": {"x": {"field": "date", "type": "temporal"},
                          "y": {"field": "price", "type": "quantitative"},
                          "color": {"field": "symbol", "type": "nominal", "title": "Symbol"}}}
        ]},
    },
    {
        "id": "la2_line_monotone", "title": "Line with Monotone Interpolation — GOOG",
        "sql": "SELECT date, price FROM pb_demo.custom_gallery.stocks WHERE symbol='GOOG' ORDER BY date",
        "fields": ["date", "price"],
        "spec": {"mark": {"type": "line", "interpolate": "monotone"},
                 "encoding": {"x": {"field": "date", "type": "temporal", "title": None},
                              "y": {"field": "price", "type": "quantitative", "title": "Price ($)"}}},
    },
    {
        "id": "la2_bump", "title": "Bump Chart — Stock Price Rank Over Time",
        "sql": "SELECT symbol, date, RANK() OVER (PARTITION BY date ORDER BY price DESC) AS rnk FROM pb_demo.custom_gallery.stocks ORDER BY date",
        "fields": ["symbol", "date", "rnk"],
        "w": 3,
        "spec": {"mark": {"type": "line", "point": True, "interpolate": "monotone"},
                 "encoding": {"x": {"field": "date", "type": "temporal", "title": None},
                              "y": {"field": "rnk", "type": "quantitative", "title": "Rank", "scale": {"reverse": True}, "axis": {"tickMinStep": 1}},
                              "color": {"field": "symbol", "type": "nominal", "title": "Symbol"}}},
    },
    {
        "id": "la2_trail_size", "title": "Trail with Varying Size — GOOG",
        "sql": "SELECT date, price FROM pb_demo.custom_gallery.stocks WHERE symbol='GOOG' ORDER BY date",
        "fields": ["date", "price"],
        "spec": {"mark": {"type": "trail"},
                 "encoding": {"x": {"field": "date", "type": "temporal", "title": None},
                              "y": {"field": "price", "type": "quantitative", "title": "Price ($)"},
                              "size": {"field": "price", "type": "quantitative", "title": "Price ($)", "legend": None}}},
    },
    {
        "id": "la2_stroke_dash", "title": "Line with Varying Stroke Dash",
        "sql": "SELECT symbol, date, price FROM pb_demo.custom_gallery.stocks ORDER BY date",
        "fields": ["symbol", "date", "price"],
        "spec": {"mark": "line",
                 "encoding": {"x": {"field": "date", "type": "temporal", "title": None},
                              "y": {"field": "price", "type": "quantitative", "title": "Price ($)"},
                              "strokeDash": {"field": "symbol", "type": "nominal", "title": "Symbol"}}},
    },
    {
        "id": "la2_dashed_part", "title": "Line with a Dashed Part — GOOG",
        "sql": "SELECT date, price, CASE WHEN price >= 400 THEN 'high' ELSE 'low' END AS seg FROM pb_demo.custom_gallery.stocks WHERE symbol='GOOG' ORDER BY date",
        "fields": ["date", "price", "seg"],
        "spec": {"mark": {"type": "line", "color": "#5593F7"},
                 "encoding": {"x": {"field": "date", "type": "temporal", "title": None},
                              "y": {"field": "price", "type": "quantitative", "title": "Price ($)"},
                              "strokeDash": {"field": "seg", "type": "nominal", "title": "Segment"}}},
    },
    {
        "id": "la2_trig", "title": "Sine and Cosine Curves",
        "sql": "SELECT i*0.2 AS x, SIN(i*0.2) AS sine, COS(i*0.2) AS cosine FROM (SELECT explode(sequence(0,63)) AS i) ORDER BY x",
        "fields": ["x", "sine", "cosine"],
        "w": 3,
        "spec": {"transform": [{"fold": ["sine", "cosine"], "as": ["fn", "value"]}],
                 "mark": "line",
                 "encoding": {"x": {"field": "x", "type": "quantitative", "title": "x"},
                              "y": {"field": "value", "type": "quantitative", "title": "f(x)"},
                              "color": {"field": "fn", "type": "nominal", "title": None}}},
    },
    {
        "id": "la2_area_gradient", "title": "Area Chart with Gradient — S&P 500",
        "sql": "SELECT date, price FROM pb_demo.custom_gallery.sp500 ORDER BY date",
        "fields": ["date", "price"],
        "spec": {"mark": {"type": "area", "line": {"color": "#5593F7"},
                          "color": {"x1": 1, "y1": 1, "x2": 1, "y2": 0, "gradient": "linear",
                                     "stops": [{"offset": 0, "color": "white"},
                                               {"offset": 1, "color": "#5593F7"}]}},
                 "encoding": {"x": {"field": "date", "type": "temporal", "title": None},
                              "y": {"field": "price", "type": "quantitative", "title": "Index"}}},
    },
    {
        "id": "la2_horizon", "title": "Horizon Graph — Seattle Max Temp",
        "sql": "SELECT date, LEAST(temp_max, 15) AS band1, GREATEST(temp_max - 15, 0) AS band2 FROM pb_demo.custom_gallery.seattle_weather ORDER BY date",
        "fields": ["date", "band1", "band2"],
        "w": 3,
        "spec": {"layer": [
            {"mark": {"type": "area", "color": "#5593F7", "opacity": 0.6},
             "encoding": {"x": {"field": "date", "type": "temporal", "title": None},
                          "y": {"field": "band1", "type": "quantitative", "title": "Temp (°C)", "scale": {"domain": [0, 15]}}}},
            {"mark": {"type": "area", "color": "#1F4E96", "opacity": 0.6},
             "encoding": {"x": {"field": "date", "type": "temporal"},
                          "y": {"field": "band2", "type": "quantitative", "scale": {"domain": [0, 15]}}}}
        ]},
    },
    {
        "id": "la2_ranks_industry", "title": "Ranks Over Time — Unemployment by Industry",
        "sql": "SELECT series, date, RANK() OVER (PARTITION BY date ORDER BY count DESC) AS rnk FROM pb_demo.custom_gallery.unemployment_across_industries ORDER BY date",
        "fields": ["series", "date", "rnk"],
        "w": 3,
        "spec": {"mark": {"type": "line", "point": True, "interpolate": "monotone"},
                 "encoding": {"x": {"field": "date", "type": "temporal", "title": None},
                              "y": {"field": "rnk", "type": "quantitative", "title": "Rank", "scale": {"reverse": True}, "axis": {"tickMinStep": 1}},
                              "color": {"field": "series", "type": "nominal", "title": "Industry"}}},
    },
    {
        "id": "g3_line_slope", "title": "Slope Chart — Iowa Electricity 2001 vs 2017",
        "sql": "SELECT source, CAST(year(year) AS STRING) AS yr, net_generation FROM pb_demo.custom_gallery.iowa_electricity WHERE year(year) IN (2001,2017) ORDER BY source, yr",
        "fields": ["source", "yr", "net_generation"],
        "spec": {"mark": {"type": "line", "point": True},
                 "encoding": {"x": {"field": "yr", "type": "ordinal", "title": None, "axis": {"labelAngle": 0}, "scale": {"padding": 0.35}},
                              "y": {"field": "net_generation", "type": "quantitative", "title": "Net generation"},
                              "color": {"field": "source", "type": "nominal", "title": "Source"}}},
    },
    {
        "id": "g3_line_conditional_axis", "title": "Conditional Axis — Seattle Max Temp",
        "sql": "SELECT date, temp_max FROM pb_demo.custom_gallery.seattle_weather ORDER BY date",
        "fields": ["date", "temp_max"],
        "w": 3,
        "spec": {"mark": "line",
                 "encoding": {"x": {"field": "date", "type": "temporal", "timeUnit": "yearmonth", "title": None,
                                    "axis": {"labelAngle": 0,
                                             "gridColor": {"condition": {"test": {"field": "value", "timeUnit": "month", "equal": 1}, "value": "#333"},
                                                           "value": "#eee"},
                                             "tickColor": {"condition": {"test": {"field": "value", "timeUnit": "month", "equal": 1}, "value": "#333"},
                                                           "value": "#ccc"}}},
                              "y": {"aggregate": "mean", "field": "temp_max", "type": "quantitative", "title": "Mean max temp (°C)"}}},
    },
    {
        "id": "g3_trail_comet", "title": "Comet Chart — Unemployment Rate 2000 → 2010",
        "sql": "SELECT series, CAST(year AS STRING) AS yr, ROUND(AVG(rate),2) AS rate FROM pb_demo.custom_gallery.unemployment_across_industries WHERE year IN (2000,2010) GROUP BY series, year ORDER BY series, yr",
        "fields": ["series", "yr", "rate"],
        "w": 3,
        "spec": {"mark": {"type": "trail"},
                 "encoding": {"x": {"field": "yr", "type": "ordinal", "title": None, "axis": {"labelAngle": 0}, "scale": {"padding": 0.3}},
                              "y": {"field": "series", "type": "nominal", "title": "Industry"},
                              "size": {"field": "rate", "type": "quantitative", "title": "Rate (%)", "scale": {"range": [0, 12]}},
                              "color": {"field": "series", "type": "nominal", "legend": None},
                              "detail": {"field": "series", "type": "nominal"}}},
    },
    {
        "id": "g3_trail_color", "title": "Colored Trail — Stock Prices",
        "sql": "SELECT symbol, date, price FROM pb_demo.custom_gallery.stocks ORDER BY date",
        "fields": ["symbol", "date", "price"],
        "spec": {"mark": {"type": "trail"},
                 "encoding": {"x": {"field": "date", "type": "temporal", "title": None},
                              "y": {"field": "price", "type": "quantitative", "title": "Price ($)"},
                              "color": {"field": "symbol", "type": "nominal", "title": "Symbol"},
                              "size": {"field": "price", "type": "quantitative", "title": "Price ($)", "legend": None}}},
    },
    {
        "id": "g3_line_skip_invalid_mid_overlay", "title": "Line with Null Gap + Points — GOOG",
        "sql": "SELECT date, CASE WHEN year(date)=2007 AND month(date) IN (6,7,8) THEN NULL ELSE price END AS price FROM pb_demo.custom_gallery.stocks WHERE symbol='GOOG' ORDER BY date",
        "fields": ["date", "price"],
        "spec": {"mark": {"type": "line", "point": True},
                 "encoding": {"x": {"field": "date", "type": "temporal", "title": None},
                              "y": {"field": "price", "type": "quantitative", "title": "Price ($)"}}},
    },
]
